version: '3.8.5' #1

services: #2
  my-first-api: #3
    build: .   #4
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"] #5
    volumes: #6
      - .:/code #7
    ports:  #8
      - "80:80"